version: "3.2"

networks:
  backend:

services:
  gradebook:
    image: henrygustavo/grade-book-api
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: grade-book-api
    ports:
      - "5001:80"
    networks:
      - backend